# Generated by Django 4.1.4 on 2023-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='div',
            field=models.CharField(default=0, max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='rollno',
            field=models.CharField(default=0, max_length=70),
        ),
    ]
