# Generated by Django 4.1.4 on 2023-01-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_div_user_rollno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Course',
        ),
    ]
